
services:
  db:
    image: mysql:9.6.0
    container_name: python-api-db
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/root_pass
      - MYSQL_DATABASE=web
      - MYSQL_USER=simas
      - MYSQL_PASSWORD=/run/secrets/user_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 25
    secrets:
      - root_pass
      - user_pass

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: python-api-web:${COMPOSE_VERSION}
    depends_on:
       db:
          condition: service_healthy
          restart: true
    container_name: web_app
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/root_pass
      - MYSQL_DATABASE=web
      - MYSQL_USER=simas
      - MYSQL_PASSWORD=/run/secrets/user_pass
      - MYSQL_HOST=python-api-db
    volumes:
      - ./files/:/app/files
    ports:
      - "8000:8000"
    networks:
      - app_network
    secrets:
      - root_pass
      - user_pass
      - pepper

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge

secrets:
  root_pass:
    file: root_pass.txt
  user_pass:
    file: user_pass.txt
  pepper:
    file: pepper.txt