apiVersion: v2
name: web
description: A Helm chart for Python API made using Flask and MySQL

type: application

version: 0.6.0

appVersion: "0.6.0"

dependencies:
  - name: mysql
    version: 14.0.3
    repository: https://charts.bitnami.com/bitnami
