
# *** Web application ***
image:
  repository: python-api-web
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1
autoscaling:
  enabled: false

nameOverride: web
containerName: web-app

web:
  # Container resources
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  # Probes
  startupProbe:
    httpGet:
      path: /web/
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30

  livenessProbe:
    httpGet:
      path: /db/
      port: http
    initialDelaySeconds: 15
    periodSeconds: 20

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false

  # Persistence
  persistence:
    name: web-pvc
    enabled: true
    size: 1Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    mountPath: /app/files

# *** Service ***
service:
  type: NodePort
  port: 8000

# *** Environment Variables ***
env:
  # Database connection
  MYSQL_DATABASE: web
  MYSQL_USER: simas
  MYSQL_HOST: ""

  # App settings
  SERVER_DEBUG: "true"
  NETWORK_PORT: 8000
  NETWORK_HOST: "0.0.0.0"
  LOG_LEVEL: "DEBUG"
  ALLOWED_DIR: "files"

# *** MySQL Dependency ***
mysql:
  enabled: true

  auth:
    database: web
    username: simas
    existingSecret: mysql-secret

  image:
    repository: bitnamilegacy/mysql
    tag: 8.4.4-debian-12-r0

  primary:
    persistence:
      enabled: true
      size: 1Gi

    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "750m"
        memory: "1Gi"

    startupProbe:
      initialDelaySeconds: 30
      failureThreshold: 60
      periodSeconds: 10

  initdbScriptsConfigMap: ""
  initdbScripts:
    01-init-createtable.sql: |-
      USE web;
  
      CREATE TABLE IF NOT EXISTS users (
          id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255),
          surname VARCHAR(255),
          password VARCHAR(255) NOT NULL,
          address VARCHAR(255),
          telephone_num VARCHAR(20),
          email VARCHAR(255) NOT NULL UNIQUE
      );
