apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webchart.fullname" . }}
  labels:
    {{- include "webchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webchart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: user-pass
                  name: user-pass
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-pass
                  name: root-pass
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  key: pepper
                  name: pepper
            - name: MYSQL_DATABASE
              value: {{ .Values.env.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.env.MYSQL_USER }}
            - name: MYSQL_HOST
              value: {{ .Values.env.MYSQL_HOST }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
