apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webchart.fullname" . }}
  labels:
    {{- include "webchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webchart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          startupProbe:
            {{- toYaml .Values.web.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12}}
          envFrom:
            - configMapRef:
                name: {{ include "webchart.fullname" . }}-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: mysql-secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: mysql-secret
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  key: pepper
                  name: pepper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.web.persistence.mountPath}}
              name: files
              readOnly: false
      volumes:
          - name: files
            persistentVolumeClaim:
              claimName: {{ include "webchart.fullname" . }}-pvc
