apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "webchart.labels" . | nindent 4 }}
  name: {{ include "webchart.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.web.persistence.storageClass }}
  accessModes:
  {{- toYaml .Values.web.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.web.persistence.size }}
