apiVersion: v1
data:
  pepper: OGY0ZTJjOWExYjBkN2YzZTVhNmM4YjlkMGYxZTJhNGM2YjhkOWYwZTFhMmM0YjZkOGYwZTlhMWIzYzVkN2U5Zg==
kind: Secret
metadata:
  labels:
    io.kompose.service: pepper
  name: pepper
type: Opaque
