apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: web
  name: web-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
